FROM debian:7.11-slim
RUN apt-get update && \
        apt-get install -y \
                bash \
                build-essential \
                net-tools \
                git \
                curl \
                wget
WORKDIR /code
